INSERT INTO service_catalog (code, name, category, group_name, subcategory, display_order, description, base_labour_minutes) VALUES
  ('diag_abs_warning_light', 'ABS Warning Light Inspection', 'diagnostics', 'diagnostics', 'general', 631, NULL, 60),
  ('diag_air_conditioning_system', 'Air conditioning system inspection', 'diagnostics', 'diagnostics', 'general', 632, NULL, 60),
  ('diag_battery_warning_light', 'Battery Warning Light Inspection', 'diagnostics', 'diagnostics', 'general', 633, NULL, 60),
  ('diag_pulls_left_right', 'Pulling System Inspection', 'diagnostics', 'diagnostics', 'general', 634, NULL, 60),
  ('diag_bulb_failure', 'Bulb Failure Inspection', 'diagnostics', 'diagnostics', 'general', 635, NULL, 60),
  ('diag_car_smoking', 'Car Smoking Inspection', 'diagnostics', 'diagnostics', 'general', 636, NULL, 60),
  ('diag_car_leaking_oil', 'Car Leaking Oil Inspection', 'diagnostics', 'diagnostics', 'general', 637, NULL, 60),
  ('diag_car_overheating', 'Car Overheating Inspection', 'diagnostics', 'diagnostics', 'general', 638, NULL, 60),
  ('diag_car_shuddering', 'Car Shuddering/Vibrating Inspection', 'diagnostics', 'diagnostics', 'general', 639, NULL, 60),
  ('diag_car_steering', 'Car Steering Inspection', 'diagnostics', 'diagnostics', 'general', 640, NULL, 60),
  ('diag_catalytic_converter', 'Catalytic Converter Inspection', 'diagnostics', 'diagnostics', 'general', 641, NULL, 60),
  ('diag_central_locking', 'Central Locking Inspection', 'diagnostics', 'diagnostics', 'general', 642, NULL, 60),
  ('diag_convertible_roof', 'Convertible roof fault diagnostic', 'diagnostics', 'diagnostics', 'general', 643, NULL, 60),
  ('diag_cooling_system', 'Cooling System Inspection', 'diagnostics', 'diagnostics', 'general', 644, NULL, 60),
  ('diag_cooling_heating', 'Cooling and Heating Inspection', 'diagnostics', 'diagnostics', 'general', 645, NULL, 60),
  ('diag_cruise_control', 'Cruise Control Inspection', 'diagnostics', 'diagnostics', 'general', 646, NULL, 60),
  ('diag_door_open', 'Door Open Inspection', 'diagnostics', 'diagnostics', 'general', 647, NULL, 60),
  ('diag_electronic_throttle', 'Electronic Throttle Control Inspection', 'diagnostics', 'diagnostics', 'general', 648, NULL, 60),
  ('diag_engine_warning_light', 'Engine Warning Light Inspection', 'diagnostics', 'diagnostics', 'general', 649, NULL, 60),
  ('diag_fuel_filler_cap', 'Fuel Filler Cap Inspection', 'diagnostics', 'diagnostics', 'general', 650, NULL, 60),
  ('diag_gear_selector_transmission', 'Gear Selector And Transmission Inspection', 'diagnostics', 'diagnostics', 'general', 651, NULL, 60),
  ('diag_handbrake', 'Handbrake Inspection', 'diagnostics', 'diagnostics', 'general', 652, NULL, 60),
  ('diag_noise_all_speeds', 'Noise At All Speeds Inspection', 'diagnostics', 'diagnostics', 'general', 653, NULL, 60),
  ('diag_noise_low_speeds', 'Noise At Slow Speeds Inspection', 'diagnostics', 'diagnostics', 'general', 654, NULL, 60),
  ('diag_noise_inside_car', 'Noise Inside Car Inspection', 'diagnostics', 'diagnostics', 'general', 655, NULL, 60),
  ('diag_noise_under_bonnet', 'Noise Under Bonnet Inspection', 'diagnostics', 'diagnostics', 'general', 656, NULL, 60),
  ('diag_noise_when_braking', 'Noise When Braking Inspection', 'diagnostics', 'diagnostics', 'general', 657, NULL, 60),
  ('diag_noise_when_starting', 'Noise When Starting Inspection', 'diagnostics', 'diagnostics', 'general', 658, NULL, 60),
  ('diag_oil_level_pressure', 'Oil Level And Pressure Inspection', 'diagnostics', 'diagnostics', 'general', 659, NULL, 60),
  ('diag_overdrive', 'Overdrive Inspection', 'diagnostics', 'diagnostics', 'general', 660, NULL, 60),
  ('diag_power_steering', 'Power Steering Inspection', 'diagnostics', 'diagnostics', 'general', 661, NULL, 60),
  ('diag_reduced_engine_power', 'Reduced Engine Power Inspection', 'diagnostics', 'diagnostics', 'general', 662, NULL, 60),
  ('diag_srs_airbag', 'SRS/Airbags Inspection', 'diagnostics', 'diagnostics', 'general', 663, NULL, 60),
  ('diag_seatbelts', 'Seatbelts Inspection', 'diagnostics', 'diagnostics', 'general', 664, NULL, 60),
  ('diag_suspension', 'Suspension Inspection', 'diagnostics', 'diagnostics', 'general', 665, NULL, 60),
  ('diag_suspension_noise', 'Suspension Noise Inspection', 'diagnostics', 'diagnostics', 'general', 666, NULL, 60),
  ('diag_traction_control', 'Traction Control Inspection', 'diagnostics', 'diagnostics', 'general', 667, NULL, 60),
  ('diag_transmission_fluid_temp', 'Transmission Fluid Temperature Inspection', 'diagnostics', 'diagnostics', 'general', 668, NULL, 60),
  ('diag_tyre_pressure_warning', 'Tyre pressure warning light inspection (TPMS)', 'diagnostics', 'diagnostics', 'general', 669, NULL, 60),
  ('diag_warning_light', 'Warning Light Inspection', 'diagnostics', 'diagnostics', 'general', 670, NULL, 60),
  ('diag_washer_system', 'Washer System Inspection', 'diagnostics', 'diagnostics', 'general', 671, NULL, 60),
  ('diag_water_car', 'Water Coming into Car Inspection', 'diagnostics', 'diagnostics', 'general', 672, NULL, 60),
  ('diag_windows', 'Windows Inspection', 'diagnostics', 'diagnostics', 'general', 673, NULL, 60)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  category = VALUES(category),
  group_name = VALUES(group_name),
  subcategory = VALUES(subcategory),
  display_order = VALUES(display_order),
  description = VALUES(description),
  base_labour_minutes = VALUES(base_labour_minutes);

INSERT INTO service_pricing (service_id, region, labour_rate_eur, parts_markup_pct, travel_fee_eur, vat_pct)
SELECT sc.id, 'UK-default', 66.39, 0.00, 0.00, 20.00
FROM service_catalog sc
WHERE sc.code IN (
  'diag_abs_warning_light',
  'diag_air_conditioning_system',
  'diag_battery_warning_light',
  'diag_pulls_left_right',
  'diag_bulb_failure',
  'diag_car_smoking',
  'diag_car_leaking_oil',
  'diag_car_overheating',
  'diag_car_shuddering',
  'diag_car_steering',
  'diag_catalytic_converter',
  'diag_central_locking',
  'diag_convertible_roof',
  'diag_cooling_system',
  'diag_cooling_heating',
  'diag_cruise_control',
  'diag_door_open',
  'diag_electronic_throttle',
  'diag_engine_warning_light',
  'diag_fuel_filler_cap',
  'diag_gear_selector_transmission',
  'diag_handbrake',
  'diag_noise_all_speeds',
  'diag_noise_low_speeds',
  'diag_noise_inside_car',
  'diag_noise_under_bonnet',
  'diag_noise_when_braking',
  'diag_noise_when_starting',
  'diag_oil_level_pressure',
  'diag_overdrive',
  'diag_power_steering',
  'diag_reduced_engine_power',
  'diag_srs_airbag',
  'diag_seatbelts',
  'diag_suspension',
  'diag_suspension_noise',
  'diag_traction_control',
  'diag_transmission_fluid_temp',
  'diag_tyre_pressure_warning',
  'diag_warning_light',
  'diag_washer_system',
  'diag_water_car',
  'diag_windows'
)
ON DUPLICATE KEY UPDATE
  labour_rate_eur = VALUES(labour_rate_eur),
  parts_markup_pct = VALUES(parts_markup_pct),
  travel_fee_eur = VALUES(travel_fee_eur),
  vat_pct = VALUES(vat_pct);
